### ISSUE TITLE
'Mesh' object has no attribute 'calc_normals' --> Blender 4.0.2

### ISSUE THREAD

**Issue by arthurvilarinho** [alessandro-zomparelli/mesh_sync#4]
Hello Alessandro, good afternoon.
I love using Mesh Sync in my everyday workflow between grasshopper and blender.

The problem is that I used the addon recently with Blender 4.0.2 and had this problem when exporting the geometry:

Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\mesh_sync.py", line 274, in execute
    simple_export(ob, ob.sync_out_path)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\mesh_sync.py", line 114, in simple_export
    mesh.calc_normals()
AttributeError: 'Mesh' object has no attribute 'calc_normals'. Did you mean: 'flip_normals'?

![image](https://github.com/alessandro-zomparelli/mesh_sync/assets/156814009/186e005b-f846-4db6-8b44-ceabc847ee56)

![image](https://github.com/alessandro-zomparelli/mesh_sync/assets/156814009/9edf30e7-2220-4b0e-8180-e23cbe76d5de)

Any Thoughts?

**Comment by alessandro-zomparelli** [comment]
Hi @arthurvilarinho ! Thanks for reporting that. I updated the code creating a new version: https://github.com/alessandro-zomparelli/mesh_sync/releases/tag/v1-0-0
Let me know if it works now :-)
